/*
 * GamePanel.java
 *
 * Created on __DATE__, __TIME__
 */

package ch.pentago.ui;

import java.awt.Color;
import java.util.LinkedList;
import java.util.Observable;
import java.util.Observer;

import javax.swing.JButton;

import ch.pentago.client.ClientState;
import ch.pentago.client.ImageLoader;
import ch.pentago.core.LocalGame;
import ch.pentago.core.Square;
import ch.pentago.xml.UserConfigManager;

/**
 * 
 * @author __USER__
 */
public class BoardPanel extends javax.swing.JPanel implements Observer {

	private static final long serialVersionUID = 2465300040954109136L;

	private LinkedList<JButton> buttons = new LinkedList<JButton>();

	private LinkedList<SquareRenderer> squares = new LinkedList<SquareRenderer>();

	/**
	 * This is a reference to the local Game Instance
	 */
	private LocalGame game;

	/** Creates new form GamePanel */
	public BoardPanel() {
		initComponents();

		squares.add(topleft_square);
		squares.add(topright_square);
		squares.add(bottomleft_square);
		squares.add(bottomright_square);

		buttons.add(tr_l_button);
		buttons.add(tr_r_button);
		buttons.add(tl_l_button);
		buttons.add(tl_r_button);
		buttons.add(br_l_button);
		buttons.add(br_r_button);
		buttons.add(bl_l_button);
		buttons.add(bl_r_button);

		for (JButton button : buttons) {
			button.setEnabled(false);
		}

		if (UserConfigManager.isInitalized()) {
			tl_r_button.setIcon(ImageLoader.getIcon("a1.png"));
			tl_l_button.setIcon(ImageLoader.getIcon("a2.png"));
			tr_r_button.setIcon(ImageLoader.getIcon("a3.png"));
			tr_l_button.setIcon(ImageLoader.getIcon("a4.png"));
			br_r_button.setIcon(ImageLoader.getIcon("a5.png"));
			br_l_button.setIcon(ImageLoader.getIcon("a6.png"));
			bl_r_button.setIcon(ImageLoader.getIcon("a7.png"));
			bl_l_button.setIcon(ImageLoader.getIcon("a8.png"));
		}
	}

	public void startGame(LocalGame game) {
		this.game = game;

		int i = 1;
		Square[] square = game.getSquares();
		for (SquareRenderer sr : squares) {
			sr.setGame(game, i);
			square[i].addObserver(this);
			i++;
		}
	}

	public void update(Observable arg0, Object arg1) {

		if (game.getTurn() == LocalGame.LOCAL) {
			turn_label.setBackground(Color.green);
			turn_label.setText("You are in turn");

			if (game.getAction() == LocalGame.PLACING) {
				for (JButton button : buttons) {
					button.setEnabled(false);
				}

				for (SquareRenderer square : squares) {
					square.setEnabled(true);
				}
			} else if (game.getAction() == LocalGame.ROTATING) {
				for (JButton button : buttons) {
					button.setEnabled(true);
				}

				for (SquareRenderer square : squares) {
					square.setEnabled(false);
				}
			}
		} else {
			if (game.getTurn() == LocalGame.REMOTE) {
				turn_label.setBackground(Color.red);
				turn_label.setText("Wait for remote user to finish turn");
			} else if (game.isFinished()) {
				// Setting win message
				turn_label.setBackground(Color.orange);
				if (game.getWinner().equals(
						ClientState.currentUser.getSessionId())) {
					turn_label.setText("Booomchaka, you won the game!");
				} else if (game.getWinner().equals("draw")) {
					turn_label.setText("The game ended with a draw result");
				} else {
					turn_label.setText("You snooze, you lose!");
				}
			}

			for (JButton button : buttons) {
				button.setEnabled(false);
			}

			for (SquareRenderer square : squares) {
				square.setEnabled(false);
			}
		}

		repaint();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">
	private void initComponents() {
		tl_r_button = new javax.swing.JButton();
		tl_l_button = new javax.swing.JButton();
		tr_r_button = new javax.swing.JButton();
		tr_l_button = new javax.swing.JButton();
		br_r_button = new javax.swing.JButton();
		br_l_button = new javax.swing.JButton();
		bl_r_button = new javax.swing.JButton();
		bl_l_button = new javax.swing.JButton();
		topright_square = new ch.pentago.ui.SquareRenderer();
		bottomleft_square = new ch.pentago.ui.SquareRenderer();
		bottomright_square = new ch.pentago.ui.SquareRenderer();
		topleft_square = new ch.pentago.ui.SquareRenderer();
		turn_label = new javax.swing.JLabel();

		setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		tl_r_button.setBorderPainted(false);
		tl_r_button.setContentAreaFilled(false);
		tl_r_button.setFocusPainted(false);
		tl_r_button.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				tl_r_buttonActionPerformed(evt);
			}
		});

		add(tl_r_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(110,
				0, 62, 62));

		tl_l_button.setBorderPainted(false);
		tl_l_button.setContentAreaFilled(false);
		tl_l_button.setFocusPainted(false);
		tl_l_button.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				tl_l_buttonActionPerformed(evt);
			}
		});

		add(tl_l_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0,
				110, 62, 62));

		tr_r_button.setBorderPainted(false);
		tr_r_button.setContentAreaFilled(false);
		tr_r_button.setFocusPainted(false);
		tr_r_button.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				tr_r_buttonActionPerformed(evt);
			}
		});

		add(tr_r_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(390,
				110, 62, 62));

		tr_l_button.setBorderPainted(false);
		tr_l_button.setContentAreaFilled(false);
		tr_l_button.setFocusPainted(false);
		tr_l_button.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				tr_l_buttonActionPerformed(evt);
			}
		});

		add(tr_l_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(270,
				0, 62, 62));

		br_r_button.setBorderPainted(false);
		br_r_button.setContentAreaFilled(false);
		br_r_button.setFocusPainted(false);
		br_r_button.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				br_r_buttonActionPerformed(evt);
			}
		});

		add(br_r_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(270,
				390, 62, 62));

		br_l_button.setBorderPainted(false);
		br_l_button.setContentAreaFilled(false);
		br_l_button.setFocusPainted(false);
		br_l_button.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				br_l_buttonActionPerformed(evt);
			}
		});

		add(br_l_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(390,
				270, 62, 62));

		bl_r_button.setBorderPainted(false);
		bl_r_button.setContentAreaFilled(false);
		bl_r_button.setFocusPainted(false);
		bl_r_button.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bl_r_buttonActionPerformed(evt);
			}
		});

		add(bl_r_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0,
				270, 62, 62));

		bl_l_button.setBorderPainted(false);
		bl_l_button.setContentAreaFilled(false);
		bl_l_button.setFocusPainted(false);
		bl_l_button.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bl_l_buttonActionPerformed(evt);
			}
		});

		add(bl_l_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(110,
				390, 62, 62));

		org.jdesktop.layout.GroupLayout topright_squareLayout = new org.jdesktop.layout.GroupLayout(
				topright_square);
		topright_square.setLayout(topright_squareLayout);
		topright_squareLayout.setHorizontalGroup(topright_squareLayout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(0, 150, Short.MAX_VALUE));
		topright_squareLayout.setVerticalGroup(topright_squareLayout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(0, 150, Short.MAX_VALUE));
		add(topright_square, new org.netbeans.lib.awtextra.AbsoluteConstraints(
				230, 70, 150, 150));

		org.jdesktop.layout.GroupLayout bottomleft_squareLayout = new org.jdesktop.layout.GroupLayout(
				bottomleft_square);
		bottomleft_square.setLayout(bottomleft_squareLayout);
		bottomleft_squareLayout.setHorizontalGroup(bottomleft_squareLayout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(0, 150, Short.MAX_VALUE));
		bottomleft_squareLayout.setVerticalGroup(bottomleft_squareLayout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(0, 150, Short.MAX_VALUE));
		add(bottomleft_square,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 150,
						150));

		org.jdesktop.layout.GroupLayout bottomright_squareLayout = new org.jdesktop.layout.GroupLayout(
				bottomright_square);
		bottomright_square.setLayout(bottomright_squareLayout);
		bottomright_squareLayout.setHorizontalGroup(bottomright_squareLayout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(0, 150, Short.MAX_VALUE));
		bottomright_squareLayout.setVerticalGroup(bottomright_squareLayout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(0, 150, Short.MAX_VALUE));
		add(bottomright_square,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230,
						150, 150));

		org.jdesktop.layout.GroupLayout topleft_squareLayout = new org.jdesktop.layout.GroupLayout(
				topleft_square);
		topleft_square.setLayout(topleft_squareLayout);
		topleft_squareLayout.setHorizontalGroup(topleft_squareLayout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(0, 150, Short.MAX_VALUE));
		topleft_squareLayout.setVerticalGroup(topleft_squareLayout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(0, 150, Short.MAX_VALUE));
		add(topleft_square, new org.netbeans.lib.awtextra.AbsoluteConstraints(
				70, 70, 150, 150));

		turn_label.setBackground(new java.awt.Color(51, 204, 255));
		turn_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		turn_label.setText("Waiting for turnmessage...");
		turn_label.setOpaque(true);
		add(turn_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(5,
				470, 440, 20));

	}// </editor-fold>//GEN-END:initComponents

	// GEN-FIRST:event_bl_l_buttonActionPerformed
	private void bl_l_buttonActionPerformed(java.awt.event.ActionEvent evt) {
		bottomleft_square.rotateLeft();
	}// GEN-LAST:event_bl_l_buttonActionPerformed

	// GEN-FIRST:event_bl_r_buttonActionPerformed
	private void bl_r_buttonActionPerformed(java.awt.event.ActionEvent evt) {
		bottomleft_square.rotateRight();
	}// GEN-LAST:event_bl_r_buttonActionPerformed

	// GEN-FIRST:event_br_l_buttonActionPerformed
	private void br_l_buttonActionPerformed(java.awt.event.ActionEvent evt) {
		bottomright_square.rotateLeft();
	}// GEN-LAST:event_br_l_buttonActionPerformed

	// GEN-FIRST:event_br_r_buttonActionPerformed
	private void br_r_buttonActionPerformed(java.awt.event.ActionEvent evt) {
		bottomright_square.rotateRight();
	}// GEN-LAST:event_br_r_buttonActionPerformed

	// GEN-FIRST:event_tr_l_buttonActionPerformed
	private void tr_l_buttonActionPerformed(java.awt.event.ActionEvent evt) {
		topright_square.rotateLeft();
	}// GEN-LAST:event_tr_l_buttonActionPerformed

	// GEN-FIRST:event_tr_r_buttonActionPerformed
	private void tr_r_buttonActionPerformed(java.awt.event.ActionEvent evt) {
		topright_square.rotateRight();
	}// GEN-LAST:event_tr_r_buttonActionPerformed

	// GEN-FIRST:event_tl_l_buttonActionPerformed
	private void tl_l_buttonActionPerformed(java.awt.event.ActionEvent evt) {
		topleft_square.rotateLeft();
	}// GEN-LAST:event_tl_l_buttonActionPerformed

	// GEN-FIRST:event_tl_r_buttonActionPerformed
	private void tl_r_buttonActionPerformed(java.awt.event.ActionEvent evt) {
		topleft_square.rotateRight();
	}// GEN-LAST:event_tl_r_buttonActionPerformed

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton bl_l_button;

	private javax.swing.JButton bl_r_button;

	private ch.pentago.ui.SquareRenderer bottomleft_square;

	private ch.pentago.ui.SquareRenderer bottomright_square;

	private javax.swing.JButton br_l_button;

	private javax.swing.JButton br_r_button;

	private javax.swing.JButton tl_l_button;

	private javax.swing.JButton tl_r_button;

	private ch.pentago.ui.SquareRenderer topleft_square;

	private ch.pentago.ui.SquareRenderer topright_square;

	private javax.swing.JButton tr_l_button;

	private javax.swing.JButton tr_r_button;

	private javax.swing.JLabel turn_label;
	// End of variables declaration//GEN-END:variables

}