/*
 * DrawTest.java
 *
 * Created on __DATE__, __TIME__
 */

package ch.pentago.ui;

import java.awt.event.KeyEvent;

import org.jdom.Element;

import ch.pentago.client.ClientState;
import ch.pentago.client.GameMessageSender;
import ch.pentago.core.LocalGame;
import ch.pentago.core.User;
import ch.pentago.network.Message;
import ch.pentago.network.MessageReceiver;


/**
 * 
 * @author __USER__
 */
public class GameWindow extends javax.swing.JFrame implements MessageReceiver {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2096577544834669415L;

	private User opponent;

	private LocalGame game;

	/** Creates new form DrawTest */
	public GameWindow(User opponent) {
		this.opponent = opponent;
		ClientState.getPublisher().subscribe(this, "chat");
		initComponents();
		game = new LocalGame(opponent);
		boardPanel2.startGame(game);
	}

	public LocalGame getGame() {
		return game;
	}

	public void receive(Message message) {
		if (message.getType().equals("chat")) {
			if (!message.isChatMessageToAll()) {
				Element chat = message.getPacket().getRootElement().getChild(
						"chat");
				chat_messages.setText(""
						+ chat_messages.getText()
						+ ClientState.getUser(chat.getAttributeValue("source"))
								.getUserName() + "> " + chat.getText() + "\n");
				chat_messages
						.setCaretPosition(chat_messages.getText().length());
			}
		}

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">
	private void initComponents() {
		jScrollPane1 = new javax.swing.JScrollPane();
		chat_messages = new javax.swing.JTextArea();
		chat_text = new javax.swing.JTextField();
		send_button = new javax.swing.JButton();
		boardPanel2 = new ch.pentago.ui.BoardPanel();
		distance_label1 = new javax.swing.JLabel();
		distance_label2 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Pentago");
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosed(java.awt.event.WindowEvent evt) {
				formWindowClosed(evt);
			}
		});

		chat_messages.setColumns(20);
		chat_messages.setEditable(false);
		chat_messages.setRows(5);
		jScrollPane1.setViewportView(chat_messages);

		chat_text.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				chat_textKeyPressed(evt);
			}
		});

		send_button.setText("send");
		send_button.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				send_buttonActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								org.jdesktop.layout.GroupLayout.TRAILING,
								layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.TRAILING)
														.add(
																org.jdesktop.layout.GroupLayout.LEADING,
																jScrollPane1,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																476,
																Short.MAX_VALUE)
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				chat_text,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				406,
																				Short.MAX_VALUE)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				send_button))
														.add(
																org.jdesktop.layout.GroupLayout.LEADING,
																layout
																		.createSequentialGroup()
																		.add(
																				distance_label1,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				boardPanel2,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				distance_label2,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)))
										.addContainerGap()));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING,
																false)
														.add(
																org.jdesktop.layout.GroupLayout.TRAILING,
																distance_label1,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																490,
																Short.MAX_VALUE)
														.add(
																boardPanel2,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(
																distance_label2,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																490,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												jScrollPane1,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												126, Short.MAX_VALUE)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(send_button)
														.add(
																chat_text,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addContainerGap()));
		pack();
	}// </editor-fold>//GEN-END:initComponents

	// GEN-FIRST:event_formWindowClosed
	private void formWindowClosed(java.awt.event.WindowEvent evt) {
		if (ClientState.inGame.get()) {
			GameMessageSender.sendChatMessage(opponent.getSessionId(), "System Message: User hast left the game");
			ClientState.currentGame = null;
			ClientState.inGame.set(false);
		}
	}// GEN-LAST:event_formWindowClosed

	// GEN-FIRST:event_chat_textKeyPressed
	private void chat_textKeyPressed(java.awt.event.KeyEvent evt) {
		if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
			send_button.doClick();
		}
	}// GEN-LAST:event_chat_textKeyPressed

	// GEN-FIRST:event_send_buttonActionPerformed
	private void send_buttonActionPerformed(java.awt.event.ActionEvent evt) {
		GameMessageSender.sendChatMessage(opponent.getSessionId(), chat_text.getText());
		chat_text.setText("");

	}// GEN-LAST:event_send_buttonActionPerformed

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private ch.pentago.ui.BoardPanel boardPanel2;

	private javax.swing.JTextArea chat_messages;

	private javax.swing.JTextField chat_text;

	private javax.swing.JLabel distance_label1;

	private javax.swing.JLabel distance_label2;

	private javax.swing.JScrollPane jScrollPane1;

	private javax.swing.JButton send_button;
	// End of variables declaration//GEN-END:variables

}