/*
 * PreferencesFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package ch.pentago.ui;

import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.ListCellRenderer;

import ch.pentago.client.ClientState;
import ch.pentago.client.ImageLoader;
import ch.pentago.core.Theme;
import ch.pentago.xml.ThemeConfigManager;
import ch.pentago.xml.UserConfigManager;

/**
 *
 * @author  sidi
 */
public class PreferencesFrame extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8260216327531559353L;

	/** Creates new form PreferencesFrame */
	public PreferencesFrame() {
		initComponents();
		setup();
		pack();
	}

	private void setup() {
		String usertheme = UserConfigManager.getUserConfigItem("client",
				"theme");
		List<Theme> list = ThemeConfigManager.getThemeList();
		ListCellRenderer theme_renderer = new ThemeListCellRenderer();
		theme_combobox.setRenderer(theme_renderer);
		DefaultComboBoxModel theme_model = (DefaultComboBoxModel) theme_combobox.getModel();
		for (Theme theme : list) {
			theme_model.addElement(theme);
			if (theme.getName().equals(usertheme)) {
				theme_combobox.setSelectedItem(theme);
			}
		}
		ListCellRenderer color_renderer = new ColorListCellRenderer(theme_combobox);
		color_combobox.setRenderer(color_renderer);
		DefaultComboBoxModel color_model = (DefaultComboBoxModel) color_combobox.getModel();
		
		color_model.addElement("white");
		color_model.addElement("black");
		color_combobox.setSelectedItem(UserConfigManager.getUserConfigItem("client", "color"));
		
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">
	private void initComponents() {
		save_button = new javax.swing.JButton();
		theme_panel = new javax.swing.JPanel();
		theme_combobox = new javax.swing.JComboBox();
		color_panel = new javax.swing.JPanel();
		color_combobox = new javax.swing.JComboBox();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		save_button.setText("Save");
		save_button.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				save_buttonActionPerformed(evt);
			}
		});

		theme_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(
				javax.swing.BorderFactory.createEtchedBorder(), "Theme"));
		theme_panel.setName("Theme");
		theme_combobox.setMinimumSize(new java.awt.Dimension(70, 80));
		theme_combobox.setPreferredSize(new java.awt.Dimension(10, 10));
		theme_combobox.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				ThemeComboBoxItemStateChanged(evt);
			}
		});

		org.jdesktop.layout.GroupLayout theme_panelLayout = new org.jdesktop.layout.GroupLayout(
				theme_panel);
		theme_panel.setLayout(theme_panelLayout);
		theme_panelLayout
				.setHorizontalGroup(theme_panelLayout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								theme_panelLayout
										.createSequentialGroup()
										.addContainerGap()
										.add(
												theme_combobox,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												242,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		theme_panelLayout
				.setVerticalGroup(theme_panelLayout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								theme_panelLayout
										.createSequentialGroup()
										.add(
												theme_combobox,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												90,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		color_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(
				javax.swing.BorderFactory.createEtchedBorder(), "Color"));

		org.jdesktop.layout.GroupLayout color_panelLayout = new org.jdesktop.layout.GroupLayout(
				color_panel);
		color_panel.setLayout(color_panelLayout);
		color_panelLayout.setHorizontalGroup(color_panelLayout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(
						color_panelLayout.createSequentialGroup()
								.addContainerGap().add(color_combobox, 0, 242,
										Short.MAX_VALUE).addContainerGap()));
		color_panelLayout.setVerticalGroup(color_panelLayout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(
						color_panelLayout.createSequentialGroup().add(
								color_combobox,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(20, Short.MAX_VALUE)));

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.add(
																				theme_panel,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
														.add(
																layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.add(
																				color_panel,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				99,
																				99,
																				99)
																		.add(
																				save_button,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				97,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				layout.createSequentialGroup().addContainerGap().add(
						theme_panel,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(
								org.jdesktop.layout.LayoutStyle.RELATED).add(
								color_panel,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(
								org.jdesktop.layout.LayoutStyle.RELATED).add(
								save_button).addContainerGap(
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));
		pack();
	}// </editor-fold>//GEN-END:initComponents

	//GEN-FIRST:event_ThemeComboBoxItemStateChanged
	private void ThemeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {
		repaint();
	}//GEN-LAST:event_ThemeComboBoxItemStateChanged

	//GEN-FIRST:event_save_buttonActionPerformed
	private void save_buttonActionPerformed(java.awt.event.ActionEvent evt) {
		Theme thm = (Theme)theme_combobox.getSelectedItem();
		UserConfigManager.setUserConfigItem("client", "theme", thm.getName());
		UserConfigManager.setUserConfigItem("client", "color", (String)color_combobox.getSelectedItem());
	
		ImageLoader.dropCache();
		if(ClientState.currentGame != null) {
			ClientState.currentGame.repaint();
		}
		this.dispose();

	}//GEN-LAST:event_save_buttonActionPerformed

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JComboBox color_combobox;

	private javax.swing.JPanel color_panel;

	private javax.swing.JButton save_button;

	private javax.swing.JComboBox theme_combobox;

	private javax.swing.JPanel theme_panel;
	// End of variables declaration//GEN-END:variables

}